"""
evaluator.py - LLM-as-Judge Evaluation System
Project: LLM Evaluation Tester (Project 1)
Author: Ankur Sharma
Week: 1, Day 2

What this does:
    - Loads test results generated by test_runner.py
    - Uses a SECOND LLM call to evaluate quality of each response
    - Scores responses on: accuracy, format_compliance, relevance, hallucination
    - Generates pass/fail results with reasoning
    - Saves full evaluation report to JSON

Key concept: LLM-as-Judge pattern
    Test Prompt --> LLM --> Response
                               |
    Expected Behavior --> Evaluator LLM --> Score + Pass/Fail + Reasoning
"""

from groq import Groq
import json
import re
import os
from datetime import datetime
from dotenv import load_dotenv

load_dotenv()

# ─────────────────────────────────────────────
# CONFIGURATION
# ─────────────────────────────────────────────

API_KEY        = os.getenv("GROQ_API_KEY")
MODEL          = "llama-3.3-70b-versatile"
EVAL_TEMP      = 0                     # ALWAYS 0 for evaluators (deterministic scoring)
EVAL_MAX_TOK   = 400
PASS_THRESHOLD = 7.0                   # Score >= 7.0 out of 10 = PASS


# ─────────────────────────────────────────────
# GROQ CLIENT
# ─────────────────────────────────────────────

client = Groq(api_key=API_KEY)


# ─────────────────────────────────────────────
# HELPER: Extract clean JSON from LLM response
# ─────────────────────────────────────────────

def extract_json(text):
    """
    Strip markdown code fences and parse JSON.

    Why this exists:
        Even when you say "return ONLY JSON", models often wrap
        their response in ```json ... ``` blocks. This function
        strips those wrappers before parsing.

        We discovered this bug in test_005 during test_runner.py run.

    Args:
        text (str): Raw LLM response (may contain markdown fences)

    Returns:
        dict | None: Parsed JSON dict, or None if parsing fails
    """
    # Remove opening fence: ```json or ```
    cleaned = re.sub(r"```(?:json)?\n?", "", text)
    # Remove closing fence
    cleaned = cleaned.replace("```", "").strip()

    try:
        return json.loads(cleaned)
    except json.JSONDecodeError:
        return None


# ─────────────────────────────────────────────
# CORE: Evaluate a single response
# ─────────────────────────────────────────────

def evaluate_response(test_case, ai_response):
    """
    Use LLM-as-Judge to score a single AI response.

    Scoring criteria:
        - accuracy (0-10):          Is the information correct?
        - format_compliance (0-10): Did it follow format instructions exactly?
        - relevance (0-10):         Did it answer what was actually asked?
        - hallucination_score (0-10): 10 = no hallucination, 0 = completely made up

    Why temperature=0 for the evaluator:
        You need CONSISTENT scores. If you run the same evaluation
        twice, you want the same score. Temperature=0 guarantees this.
        Using temperature=0.7 here would mean two runs of the same
        test could give different pass/fail results - unacceptable
        in a QA system.

    Args:
        test_case (dict): Contains user_prompt and expected_behavior
        ai_response (str): The response we are evaluating

    Returns:
        dict: Evaluation result with scores, pass/fail, reasoning
    """

    # ── Evaluator system prompt ──────────────────────────────────────
    evaluator_system_prompt = """You are a strict, objective AI quality evaluator.
Your only job is to evaluate AI responses and return a JSON score object.

Scoring rules:
- Be STRICT. A score of 10 means absolutely flawless. Most responses score 6-8.
- Deduct points for: truncated responses, extra unwanted formatting,
  wrong tone, vague answers, hallucinated facts, ignoring instructions.
- hallucination_score: 10 = zero hallucination, 0 = completely fabricated.
- format_compliance: 10 = followed format instructions perfectly.
  Deduct if: response has unwanted backticks, extra explanation,
  wrong structure, or incorrect length.

Return ONLY this exact JSON structure. No text before or after it:
{
  "accuracy": <integer 0-10>,
  "format_compliance": <integer 0-10>,
  "relevance": <integer 0-10>,
  "hallucination_score": <integer 0-10>,
  "overall_score": <float, average of the four scores above>,
  "pass": <true if overall_score >= 7.0, else false>,
  "reasoning": "<one sentence explaining the scores>",
  "issues_found": ["<specific issue 1>", "<specific issue 2>"]
}"""

    # ── Evaluation prompt ────────────────────────────────────────────
    evaluation_prompt = f"""Evaluate the AI response below.

ORIGINAL QUESTION ASKED:
{test_case['user_prompt']}

EXPECTED BEHAVIOR (what a perfect response looks like):
{test_case['expected_behavior']}

ACTUAL AI RESPONSE:
{ai_response}

Score this response strictly against the expected behavior."""

    # ── API call ─────────────────────────────────────────────────────
    try:
        response = client.chat.completions.create(
            model=MODEL,
            messages=[
                {"role": "system", "content": evaluator_system_prompt},
                {"role": "user",   "content": evaluation_prompt}
            ],
            temperature=EVAL_TEMP,
            max_tokens=EVAL_MAX_TOK
        )

        raw_eval  = response.choices[0].message.content
        eval_data = extract_json(raw_eval)

        if eval_data:
            # Recalculate overall_score in Python to avoid model math errors
            scores = [
                eval_data.get("accuracy",           0),
                eval_data.get("format_compliance",  0),
                eval_data.get("relevance",          0),
                eval_data.get("hallucination_score", 0)
            ]
            eval_data["overall_score"] = round(sum(scores) / len(scores), 2)
            eval_data["pass"]          = eval_data["overall_score"] >= PASS_THRESHOLD
            eval_data["tokens_used"]   = response.usage.total_tokens
            eval_data["status"]        = "success"
        else:
            # JSON parse failed - capture raw response for debugging
            eval_data = {
                "status":        "parse_error",
                "raw_response":  raw_eval,
                "pass":          False,
                "overall_score": 0,
                "reasoning":     "Evaluator returned non-JSON response",
                "issues_found":  ["JSON parse failed"]
            }

        return eval_data

    except Exception as e:
        return {
            "status":        "api_error",
            "error":         str(e),
            "pass":          False,
            "overall_score": 0,
            "reasoning":     f"API call failed: {str(e)}",
            "issues_found":  ["API error"]
        }


# ─────────────────────────────────────────────
# MAIN: Run evaluation on test_runner.py results
# ─────────────────────────────────────────────

def run_evaluation(test_results_file):
    """
    Load test_runner.py results and evaluate every response.

    Flow:
        1. Load JSON file produced by test_runner.py
        2. For each successful test result, call evaluate_response()
        3. Track pass/fail counts and token usage
        4. Save full evaluation report to JSON
        5. Print summary to terminal

    Args:
        test_results_file (str): Path to test_runner output JSON file

    Returns:
        dict: Complete evaluation report
    """

    # ── Load test results ────────────────────────────────────────────
    if not os.path.exists(test_results_file):
        print(f"\n❌ File not found: {test_results_file}")
        print("   Make sure you run test_runner.py first.")
        return None

    with open(test_results_file, "r") as f:
        test_data = json.load(f)

    results_to_eval = test_data.get("results", [])

    print("\n" + "=" * 60)
    print("🔍 STARTING EVALUATION RUN (LLM-as-Judge)")
    print("=" * 60)
    print(f"Test results file : {test_results_file}")
    print(f"Responses to eval : {len(results_to_eval)}")
    print(f"Evaluator model   : {MODEL}")
    print(f"Evaluator temp    : {EVAL_TEMP}  ← deterministic, always 0")
    print(f"Pass threshold    : {PASS_THRESHOLD}/10")

    evaluated_results  = []
    total_eval_tokens  = 0
    passed             = 0
    failed             = 0

    # ── Evaluate each test result ────────────────────────────────────
    for result in results_to_eval:

        # Skip tests that failed at the API call level
        if result.get("status") != "success":
            print(f"\n⚠️  Skipping {result.get('test_id')} — original test failed")
            continue

        print(f"\n{'=' * 60}")
        print(f"Evaluating : {result['test_name']}")
        print(f"Test ID    : {result['test_id']}")
        print(f"Category   : {result['category']}")
        print("-" * 60)

        evaluation = evaluate_response(
            test_case={
                "user_prompt":       result["user_prompt"],
                "expected_behavior": result["expected_behavior"]
            },
            ai_response=result["ai_response"]
        )

        # ── Display individual result ────────────────────────────────
        if evaluation["status"] == "success":

            verdict = "✅ PASS" if evaluation["pass"] else "❌ FAIL"
            print(f"Verdict    : {verdict}")
            print(f"Overall    : {evaluation['overall_score']}/10")
            print(f"  Accuracy          : {evaluation.get('accuracy', 'N/A')}/10")
            print(f"  Format compliance : {evaluation.get('format_compliance', 'N/A')}/10")
            print(f"  Relevance         : {evaluation.get('relevance', 'N/A')}/10")
            print(f"  Hallucination     : {evaluation.get('hallucination_score', 'N/A')}/10")
            print(f"Reasoning  : {evaluation.get('reasoning', '')}")

            issues = evaluation.get("issues_found", [])
            if issues:
                print(f"Issues     : {', '.join(issues)}")

            print(f"Eval tokens: {evaluation.get('tokens_used', 0)}")

            if evaluation["pass"]:
                passed += 1
            else:
                failed += 1

            total_eval_tokens += evaluation.get("tokens_used", 0)

        else:
            # Evaluation itself failed
            print(f"⚠️  Evaluation error: {evaluation.get('error', evaluation.get('reasoning', 'Unknown'))}")
            failed += 1

        # Merge original result with evaluation scores
        combined = {**result, "evaluation": evaluation}
        evaluated_results.append(combined)

    # ── Summary stats ────────────────────────────────────────────────
    total_evaluated = passed + failed
    pass_rate = (passed / total_evaluated * 100) if total_evaluated > 0 else 0

    # Collect overall scores for average
    all_scores = [
        r["evaluation"]["overall_score"]
        for r in evaluated_results
        if r.get("evaluation", {}).get("status") == "success"
    ]
    avg_score = round(sum(all_scores) / len(all_scores), 2) if all_scores else 0

    summary = {
        "run_timestamp":      datetime.now().isoformat(),
        "source_file":        test_results_file,
        "evaluator_model":    MODEL,
        "evaluator_temp":     EVAL_TEMP,
        "pass_threshold":     PASS_THRESHOLD,
        "total_evaluated":    total_evaluated,
        "passed":             passed,
        "failed":             failed,
        "pass_rate_pct":      round(pass_rate, 1),
        "avg_overall_score":  avg_score,
        "eval_tokens_used":   total_eval_tokens
    }

    # ── Print final summary ──────────────────────────────────────────
    print("\n" + "=" * 60)
    print("📊 EVALUATION SUMMARY")
    print("=" * 60)
    print(f"✅ Passed           : {passed}")
    print(f"❌ Failed           : {failed}")
    print(f"📈 Pass rate        : {pass_rate:.1f}%")
    print(f"⭐ Avg score        : {avg_score}/10")
    print(f"🔢 Eval tokens used : {total_eval_tokens}")
    print("=" * 60)

    # ── Per-test score table ─────────────────────────────────────────
    print("\n📋 PER-TEST BREAKDOWN:")
    print(f"{'Test':<45} {'Score':>7} {'Result':>8}")
    print("-" * 62)
    for r in evaluated_results:
        ev      = r.get("evaluation", {})
        score   = ev.get("overall_score", 0)
        verdict = "PASS ✅" if ev.get("pass") else "FAIL ❌"
        print(f"{r['test_name']:<45} {score:>6.1f}  {verdict:>8}")

    # ── Save evaluation report ───────────────────────────────────────
    os.makedirs("test_results", exist_ok=True)
    output_file = f"test_results/evaluation_{datetime.now().strftime('%Y%m%d_%H%M%S')}.json"

    output = {
        "summary":            summary,
        "evaluated_results":  evaluated_results
    }

    with open(output_file, "w") as f:
        json.dump(output, f, indent=2)

    print(f"\n💾 Full report saved to: {output_file}")
    print("=" * 60)

    return output


# ─────────────────────────────────────────────
# ENTRY POINT
# ─────────────────────────────────────────────

if __name__ == "__main__":

    # ── Find the most recent test_runner output automatically ────────
    results_dir = "test_results"

    if not os.path.exists(results_dir):
        print("❌ No test_results folder found. Run test_runner.py first.")
    else:
        # Get all test_run_*.json files (not evaluation files)
        run_files = sorted([
            f for f in os.listdir(results_dir)
            if f.startswith("test_run_") and f.endswith(".json")
        ])

        if not run_files:
            print("❌ No test run files found. Run test_runner.py first.")
        else:
            # Use the most recent file automatically
            latest = os.path.join(results_dir, run_files[-1])
            print(f"📂 Using latest test run: {latest}")
            run_evaluation(latest)
